# Generated by Django 3.2.23 on 2024-01-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_cost',
            new_name='shipping_cost',
        ),
    ]
