# Generated by Django 3.2.23 on 2024-02-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_shopping_cart',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
